CREATE DATABASE EMPRESA

USE EMPRESA

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO VARCHAR(1) NOT NULL CHECK (SEXO IN ('M','F')), --ENUM
	NASCIMENTO DATE NOT NULL
)
GO

DROP TABLE TELEFONE

CREATE TABLE TEL(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN ('CEL', 'COM')), --ENUM
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

--REFERENCIANDO CHAVES PK E FK

ALTER TABLE TEL ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

--POPULANDO DADOS NAS TABELAS

INSERT INTO PESSOA VALUES ('ANTONIO', 'M', '1981-02-13')
INSERT INTO PESSOA VALUES ('DANIEL', 'M', '1985-03-18')
INSERT INTO PESSOA VALUES ('CLEIDE', 'F', '1979-10-13')

INSERT INTO TEL VALUES ('CEL','9879008',1)
INSERT INTO TEL VALUES ('COM','8757909',1)
INSERT INTO TEL VALUES ('CEL','9875890',2)
INSERT INTO TEL VALUES ('CEL','9347689',2)
INSERT INTO TEL VALUES ('COM','2998689',3)
INSERT INTO TEL VALUES ('COM','2098978',2)
INSERT INTO TEL VALUES ('CEL','9008679',3)
GO
--TRABALHANDO COM PROCEDURES ESTATICAS

CREATE PROC SOMA
AS
	SELECT 10 + 10 AS SOMA
GO

--EXECUTANDO A PROCEDURE ESTATICA

EXEC SOMA
GO
--PROCEDURES DINAMICAS / COM PARAMETROS

CREATE PROC CONTA @NUM1 INT, @NUM2 INT
AS
	SELECT @NUM1 + @NUM2 AS RESULTADO
GO

--EXECUTANDO A PROCEDURA DINAMICA

EXEC CONTA 90, 78
GO

--APAGANDO UMA PROCEDURE

DROP PROC CONTA
GO

--PROCEDURES COM TABELAS

SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TEL
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

--CRIANDO UMA PROCEDURE -> TRAZER OS TELEFONES DE ACORDO COM O TIPO PASSADO
CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TEL
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
GO

EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO

--PARAMETROS DE OUTPUT
SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TEL
GROUP BY TIPO
GO

--CRIANDO A PROCEDURE COM PARAMETROS DE ENTRADA E DE SAIDA
CREATE PROC GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TEL
	WHERE TIPO = @TIPO
GO

--EXECUÇÃO DA PROC COM PARAMETRO DE SAIDA
--TRANSACTION SQL -> LINGUAGEM QUE O SQL SERVER TRABALHA

DECLARE @SAIDA INT 
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO