CREATE DATABASE EMPRESA

USE EMPRESA

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO VARCHAR(1) NOT NULL CHECK (SEXO IN ('M','F')), --ENUM
	NASCIMENTO DATE NOT NULL
)
GO

DROP TABLE TELEFONE

CREATE TABLE TEL(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN ('CEL', 'COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

--REFERENCIANDO CHAVES PK E FK

ALTER TABLE TEL ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

--POPULANDO DADOS NAS TABELAS

INSERT INTO PESSOA VALUES ('ANTONIO', 'M', '1981-02-13')
INSERT INTO PESSOA VALUES ('DANIEL', 'M', '1985-03-18')
INSERT INTO PESSOA VALUES ('CLEIDE', 'F', '1979-10-13')

INSERT INTO TEL VALUES ('CEL','9879008',1)
INSERT INTO TEL VALUES ('COM','8757909',1)
INSERT INTO TEL VALUES ('CEL','9875890',2)
INSERT INTO TEL VALUES ('CEL','9347689',2)
INSERT INTO TEL VALUES ('COM','2998689',3)
INSERT INTO TEL VALUES ('COM','2098978',2)
INSERT INTO TEL VALUES ('CEL','9008679',3)